#annotation feature flags
#https://github.com/Dynatrace/dynatrace-operator/blob/main/pkg/api/v1beta1/dynakube/feature_flags.go
#https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-k8s/reference/dynakube-feature-flags
#
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: "name of the K8s to show inside dynatrace" #change me
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  apiUrl: https://${environment-id}.live.dynatrace.com/api  #change 'enviroment-id' to your saas tenant
  skipCertCheck: false
  tokens: "dynakube"
  enableIstio: false #set to true when using service mesh istio

#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: easytravel
#  labels:
#    instrumentation: oneagent

  namespaceSelector:
    matchLabels:
      instrumentation: oneagent


  oneAgent:
    # Enables Cloud native fullstack monitoring and changes its settings
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExists
          key: node-role.kubernetes.io/control-plane
          operator:  ActiveGate instances.


  activeGate:

    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      - metrics-ingest

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi