#annotation feature flags
#https://github.com/Dynatrace/dynatrace-operator/blob/main/src/api/v1beta1/dynakube/feature_flags.go
#https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-k8s/reference/dynakube-feature-flags
#
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: "name of the K8s to show inside dynatrace" #change me
  namespace: dynatrace
  # Automatically connect the kubernetes api to the dynatrace tenant endpoint to enable kubernetes monitoring.
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"


spec:
 
  apiUrl: https://ENVIRONMENTID.live.dynatrace.com/api  #change 'enviroment-id' to your saas tenant
  skipCertCheck: false

  oneAgent:
  # Enables host only monitoring and changes its settings
    hostMonitoring:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists

  activeGate:

    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      - metrics-ingest

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi