#annotation feature flags
#https://github.com/Dynatrace/dynatrace-operator/blob/main/src/api/v1beta1/dynakube/feature_flags.go
#
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/oneagent-readonly-host-fs: "false"
spec:
  apiUrl: https://${environment-id}.live.dynatrace.com/api
  skipCertCheck: false

  oneAgent:
    # Enables Cloud native fullstack monitoring and changes its settings
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists

  activeGate:

    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      - metrics-ingest

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi