#annotation feature flags
#https://github.com/Dynatrace/dynatrace-operator/blob/main/src/api/v1beta1/dynakube/feature_flags.go
#https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-k8s/reference/dynakube-feature-flags
#
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: "name of k8s cluster to show inside dynatrace" #change me
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/oneagent-initial-connect-retry-ms: "6000" #use this when using sidecar pods 

spec:
  apiUrl: https://${environment-id}.live.dynatrace.com/api #change 'environment id' to your saas tenant
  skipCertCheck: false

  oneAgent:
    # Enables Application Only monitoring and changes its settings
    applicationMonitoring:
      useCSIDriver: false  #disables the use of CSI
      
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExists
          key: node-role.kubernetes.io/control-plane
          operator:  ActiveGate instances.


  activeGate:

    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      - metrics-ingest

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi