apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/injection-readonly-volume: "true"
spec:
  apiUrl: https://${environment-id}.live.dynatrace.com/api
  skipCertCheck: false

  oneAgent:
    # Enables Application Only monitoring and changes its settings
    applicationMonitoring:
      # useCSIDriver: false (deprecated injection-readonly-volume fixes this)
      
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExists
          key: node-role.kubernetes.io/control-plane
          operator:  ActiveGate instances.


  activeGate:

    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
      - metrics-ingest

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi